-- MySQL Script generated by MySQL Workbench
-- Thu Jun 13 15:43:34 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema shine_parameter_list
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `shine_parameter_list` ;

-- -----------------------------------------------------
-- Schema shine_parameter_list
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shine_parameter_list` DEFAULT CHARACTER SET utf8 ;
USE `shine_parameter_list` ;

-- -----------------------------------------------------
-- Table `shine_parameter_list`.`accelerator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`accelerator` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`accelerator` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shine_parameter_list`.`attribute`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`attribute` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`attribute` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shine_parameter_list`.`reference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`reference` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`reference` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NULL DEFAULT NULL,
  `Author` VARCHAR(45) NULL DEFAULT NULL,
  `Publication` VARCHAR(45) NULL DEFAULT NULL,
  `URL` VARCHAR(45) NULL DEFAULT NULL,
  `Keywords` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shine_parameter_list`.`unit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`unit` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`unit` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shine_parameter_list`.`parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`parameter` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`parameter` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Unit_id` INT(11) NULL DEFAULT NULL,
  `Definition` VARCHAR(500) NULL DEFAULT NULL,
  `Date_modified` DATE NULL DEFAULT NULL,
  `Reference_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_unit_id` (`Unit_id` ASC),
  INDEX `fk_reference_id_idx` (`Reference_id` ASC),
  CONSTRAINT `fk_reference_id`
    FOREIGN KEY (`Reference_id`)
    REFERENCES `shine_parameter_list`.`reference` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_unit_id`
    FOREIGN KEY (`Unit_id`)
    REFERENCES `shine_parameter_list`.`unit` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shine_parameter_list`.`version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`version` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`version` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `Number` INT(11) NULL DEFAULT NULL,
  `acclerator_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_acclerator_id_idx` (`acclerator_id` ASC),
  CONSTRAINT `fk_acclerator_id`
    FOREIGN KEY (`acclerator_id`)
    REFERENCES `shine_parameter_list`.`accelerator` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shine_parameter_list`.`division`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`division` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`division` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shine_parameter_list`.`subdivision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`subdivision` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`subdivision` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `division_id` INT(11) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_division_id_idx` (`division_id` ASC),
  CONSTRAINT `fk_division_id`
    FOREIGN KEY (`division_id`)
    REFERENCES `shine_parameter_list`.`division` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shine_parameter_list`.`leader`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`leader` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`leader` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shine_parameter_list`.`system`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`system` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`system` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `subdivision_id` INT(11) NULL,
  `leader_id` INT(11) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_subdivision_id_idx` (`subdivision_id` ASC),
  INDEX `fk_leader_id_idx` (`leader_id` ASC),
  CONSTRAINT `fk_subdivision_id`
    FOREIGN KEY (`subdivision_id`)
    REFERENCES `shine_parameter_list`.`subdivision` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_leader_id`
    FOREIGN KEY (`leader_id`)
    REFERENCES `shine_parameter_list`.`leader` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shine_parameter_list`.`data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`data` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`data` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `Value` VARCHAR(200) NULL DEFAULT NULL,
  `acceptance` VARCHAR(200) NULL DEFAULT NULL,
  `image` LONGBLOB NULL,
  `Date_modified` DATE NULL DEFAULT NULL,
  `Attribute_id` INT(11) NULL DEFAULT NULL,
  `Parameter_id` INT(11) NULL DEFAULT NULL,
  `Comment` VARCHAR(80) NULL DEFAULT NULL,
  `Status` VARCHAR(45) NULL DEFAULT NULL,
  `Version_id` INT(11) NULL DEFAULT NULL,
  `system_id` INT(11) NULL,
  `attachment` VARCHAR(100) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_parameter_id_idx` (`Parameter_id` ASC),
  INDEX `fk_attribute_id_idx` (`Attribute_id` ASC),
  INDEX `fk_version_id_idx` (`Version_id` ASC),
  INDEX `fk_system_id_idx` (`system_id` ASC),
  CONSTRAINT `fk_attribute_id`
    FOREIGN KEY (`Attribute_id`)
    REFERENCES `shine_parameter_list`.`attribute` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parameter_id`
    FOREIGN KEY (`Parameter_id`)
    REFERENCES `shine_parameter_list`.`parameter` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_version_id`
    FOREIGN KEY (`Version_id`)
    REFERENCES `shine_parameter_list`.`version` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_system_id`
    FOREIGN KEY (`system_id`)
    REFERENCES `shine_parameter_list`.`system` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `shine_parameter_list`.`history_data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shine_parameter_list`.`history_data` ;

CREATE TABLE IF NOT EXISTS `shine_parameter_list`.`history_data` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `data_id` INT(11) NOT NULL,
  `value` VARCHAR(200) NULL DEFAULT NULL,
  `date_modified` DATE NULL DEFAULT NULL,
  `modified_reference` VARCHAR(200) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_data_id_idx` (`data_id` ASC),
  CONSTRAINT `fk_data_id`
    FOREIGN KEY (`data_id`)
    REFERENCES `shine_parameter_list`.`data` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
